### ISSUE TITLE
Guiding Questions

### ISSUE THREAD

**Issue by axiomista** [NorthwestGreenChemistry/PrISM#32]
Create JSON files for guiding questions from existing sheet.

**1** is mostly complete
**2** is being worked by V @axiomista 
**6-7** are being worked by @drunkONdata (?)

**Comment by axiomista** [comment]
@AmeliaNestler we'll need you to review this content please. I can show you how to look at it in VS Code for easy reading. 🙃

**Comment by axiomista** [comment]
Fixed GQ 2!

**Comment by sjgllghr** [comment]
Basics of all of these have been included now. Still missing dynamic questions and some other details.
